name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  token: # ${{secrets.GITHUB_TOKEN}}
    description: 'github token'
    required: true
    default: ''
  github-head-branch-name: # ${GITHUB_REF#refs/heads/}
    description: 'Github name of Head branch'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
